spring:
  application:
    name: dubbo-demo-provider

dubbo:
  application:
    name: dubbodo
  registry:
    address: zookeeper://110.40.140.47:2181
    group: demo1
  protocol:
    port: 20880
    name: dubbo

server:
  port: 8088
