spring:
  application:
    name: dubbo-demo-provider


dubbo:
  application:
    name: dubbodo
  registry:
    username: test
    password: test
    address: nacos://10.10.101.246:32576
    timeout: 3000
  protocol:
    port: 20880
    name: dubbo

