spring:
  application:
    name: dubbo-demo-provider


dubbo:
  application:
    name: dubbodo
  registries:
    beijing:
      address: zookeeper://10.10.101.28:30914
      group: demo1

  protocol:
    port: 20880
    name: dubbo

#logging:
#  level:
#    root: debug
