spring:
  application:
    name: dubbo-demo-provider

# nacos版本为2.0.3 nacos用户名密码默认为 nacos/nacos
dubbo:
  application:
    name: dubbodo
  registry:
    username: test
    password: test
    address: nacos://10.10.101.246:32576
    timeout: 3000
  protocol:
    port: 20880
    name: dubbo

