apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: middleware
      app.kubernetes.io/name: mysql
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: middleware
        app.kubernetes.io/name: mysql
        version: v1
    spec:
      automountServiceAccountToken: true
      containers:
        - env:
            - name: MYSQL_ROOT_PASSWORD
              value: Ab123456
            - name: TZ
              value: Asia/Shanghai
          image: 10.10.102.113:8443/devops-release/mysql:5.7.35
          imagePullPolicy: IfNotPresent
          name: mysql
          ports:
            - containerPort: 3306
              name: tcp
              protocol: TCP
          resources:
            limits:
              cpu: "2"
              memory: 4Gi
            requests:
              cpu: 100m
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ipFamilyPolicy: SingleStack
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app.kubernetes.io/instance: middleware
    app.kubernetes.io/name: mysql
  sessionAffinity: None
  type: ClusterIP